services:
  worker1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      STORAGE_METHOD: ${STORAGE_METHOD}
    networks:
      - network_rinha
    volumes:
      - volume_rinha:/app/docs
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "162.5MB"
  worker2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      STORAGE_METHOD: ${STORAGE_METHOD}
    networks:
      - network_rinha
    volumes:
      - volume_rinha:/app/docs
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "162.5MB"

  loadbalancer:
    image: haproxytech/haproxy-alpine:2.4
    depends_on:
      - worker1
      - worker2
    networks:
      - network_rinha

    ports:
      - "9999:80"

    volumes:
      - ./docker/HAProxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "25MB"

volumes:
  volume_rinha:

networks:
  network_rinha:
    driver: bridge
